Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/BlockLength:
  CountComments: false
  Max: 30

Metrics/ClassLength:
  CountComments: false
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - bin/**/*
    - node_modules/**/*
  NewCops: enable


Style/ClassAndModuleChildren:
  Enabled: false