Documentation:
  Enabled: false

LineLength:
  Max: 100
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 20

MethodLength:
  CountComments: false
  Max: 15

BlockLength:
  CountComments: false
  Max: 30
  Exclude:
    - spec/**/*

ClassLength:
  CountComments: false
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - spec/**/*
    - db/**/*
    - config/**/*
    - bin/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/EmptyLinesAroundClassBody:
  Enabled: false